# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c8dcdb67ffa90c608447ea3722143d35fcb93f7ff145e0d59b396f3ff9ced96015547188bdfefff79beb6798e81e124691415fa4297ab44c5da9f28d4629860
  tags: healthcare,nasa,open source
  twitter:
    consumer_key: hfGV2pa0sXG6YCAq7iNRcMllA
    consumer_secret: kh0mKSqyMCqDaPlHka0d2UUodir8LVOM3CroEJPTBeBOEuFO79
    access_token: 45627600-fGyZkN9F49kYouZ19CUTKasxq1PlQJR90wUqixqdx
    access_token_secret: chTNcSGs4uTHiXffAAlLHGLzuUHJrqJNCk1d1bzhteF4s

test:
  secret_key_base: acbcd2d7c445a29300d046950a4da545df73d9bf6d0084fec50572383f924021a5a0196d83d222a5583e0d6478586f2fb1dc8cc56e7f4304c644198912b8b9c4
  tags: healthcare,nasa,open source
  twitter:
    consumer_key: hfGV2pa0sXG6YCAq7iNRcMllA
    consumer_secret: kh0mKSqyMCqDaPlHka0d2UUodir8LVOM3CroEJPTBeBOEuFO79
    access_token: 45627600-fGyZkN9F49kYouZ19CUTKasxq1PlQJR90wUqixqdx
    access_token_secret: chTNcSGs4uTHiXffAAlLHGLzuUHJrqJNCk1d1bzhteF4s

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
